CHANGELOG.md, README.md, docs/troubleshooting.md, docs/v6_upgrade.md, lib/install/config/webpack/base.js, lib/install/config/webpack/development.js, lib/install/config/webpack/production.js, lib/install/config/webpack/test.js, lib/install/config/webpack/webpack.config.js, lib/webpacker/runner.rb, package/index.js, test/dev_server_runner_test.rb, test/webpack_runner_test.rb
See original PR: https://github.com/rails/webpacker/pull/3240
Let's have the webpack config for rails/webpacker match [jsbundling-rails](https://github.com/rails/jsbundling-rails) and use `/webpack.config.js`.
1. Simplicity and DRY. The default install was already cleaned up so
there are no differences between installing test.js, development.js,
and prododuction.js. This is just more clutter for people to dig
through.
2. Avoid confusion. Most rails developers think about the RAILS_ENV.
It's not at all obvious that old configuration file used was based on
the NODE_ENV.  And what if you wanted to adjust the configuration based
on the RAILS_ENV. Surely, you could have gotten confused. Additionally,
the default of using NODE_ENV for building a Node file was also
non-obvious.
3. Easy upgrade. …
=> Use single webpack config for rails/webpacker

docs/v6_upgrade.md
The gem has been renamed so we should reference new one in the upgrade guide.
For now, it needs also `require: 'webpacker'` in the gemfile to serve as a drop in replacement. I guess something like that might need to be documented if `webpacker` remains internally used naming
=> Update v6_upgrade.md to reference new gem name

README.md, docs/v6_upgrade.md, package.json, package/environments/base.js, yarn.lock
Addresses #16 
Webpack 5 [supports Yarn PnP out of the box](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#resolving) so the `PnpWebpackPlugin` should be no longer needed and included by default.
=> Remove pnp-webpack-plugin

README.md, lib/install/template.rb
Addresses #15 
Removes addition of `node_modules` into Rails asset load path and adds section to the readme to explain when it might be useful and how to enable it
=> Remove automatic addition of node_modules into rails asset load path

Gemfile.lock, lib/webpacker/helper.rb, test/helper_test.rb
Addresses #17
Adapted from [rails#3083](https://github.com/rails/webpacker/pull/3083) by @guillaumebriday
Multiple calls to `javascript_pack_tag` and `stylesheet_pack_tag` will now raise an error as they can result with duplicate files being loaded
=> Raise on multiple invocations of javascript_pack_tag and stylesheet_pack_tag helpers

README.md
Updates the notes to reflect the fact that Rails v6 ships with rails/webpacker by default and will need a manual installation/upgrade if users wish to use shakapacker
=> Update the docs to make migration and installation bit clearer

docs/v6_upgrade.md
webpacker binstubs have been renamed in https://github.com/rails/webpacker/pull/3252 but that was after rc-6 release.
Since shakapacker now includes new names, we should mention this in the upgrade guide from rails/webpacker rc-6
Not critical for the app to run but it standardises the approach
=> Mention renaming old webpacker binstubs

package.json
PR #21 removed pnp-webpack-plugin as a dev dependency but did not remove
it from the peer dependency list.
Worse case, users see npm warnings in console about umet peer dependencies.
=> Remove pnp-webpack-plugin as a peer dependency

docs/customizing_babel_config.md
babel-plugin-transform-react-remove-prop-types should be under plugins not under presets
=> React bable.config.js plugin fix

README.md
Closes https://github.com/shakacode/shakapacker/issues/35
We've had Yarn v2 support for a bit but requirement to opt out of Plug'n'Play behaviour was buried in the changelog. This should make this much clearer
=> Clarify Yarn v2 usage

CHANGELOG.md, package/rules/file.js
Closes https://github.com/shakacode/shakapacker/issues/44
During Webpacker v6 development, a change was made to move away from file-loader to webpack built-in asset modules. Along the way we've lost an ability to retain the folder structure though - all static assets are output in the `static` folder regardless of their original nesting.
This creates two issues:
- you can no longer reference the asset with the folder name (i.e. `<%= image_pack_tag "homepage/logo.png" %>`  will not work as `logo.png` will be lifted from its original folder into `static`
- clashing file name will result in unpredictable results - if you have same filename `logo.png` in multiple places, you cannot reliably reference it with a pack helper as it might refer to any of those in a manifest.
Rather than trying to …
=> Retain subdirectory structure of static assets when compiled

CHANGELOG.md, Gemfile.lock
- Updates Gemfile.lock to make tests happy
- Updates the year in the changelog (I feel we've all lost track of what year it is since 2020 😆 )
=> Release updates

Gemfile.lock
https://github.com/shakacode/shakapacker/commit/756318738dda09d6432d8b06418ad40abf98cd11 breaks CI 💔 
Like https://github.com/shakacode/shakapacker/runs/5090267102.
It may be better to remove `Gemfile.lock` maintenance easier.
In this PR, I just updated gem version.
=> Fix shakapacker version in Gemfile.lock to fix CI

docs/using_esbuild_loader.md, docs/using_swc_loader.md
In `RAILS_ENV=production`, shakapacker sets `NODE_ENV` as `production` in some places:
- https://github.com/shakacode/shakapacker/blob/v6.1.1/lib/tasks/webpacker/yarn_install.rake#L5-L7
- https://github.com/shakacode/shakapacker/blob/v6.1.1/lib/tasks/yarn.rake#L11-L13
All node modules that are installed via `-D` option will be ignored in `NODE_ENV=production`.
However, we need SWC dependencies in production.
So, these modules should be installed as `dependencies`, not a `devDependencies`.
=> Fix SWC & esbuild configuration for production in doc

CHANGELOG.md
A previous version of v6.1.1 is v6.1.0.
=> Fix compare link in CHANGELOG.md

docs/using_swc_loader.md
The correct config key is `webpack_loader` not `webpacker_loader`.
=> Minor SWC documentation fix

README.md
I found that the supplied example doesn't work with 6.1.1, as the manifest has static files at `static/` instead of `images/`.
=> Fix asset_pack_path example

CHANGELOG.md, README.md, package/rules/__tests__/file.js, package/rules/__tests__/index.js, package/rules/__tests__/raw.js, package/rules/file.js, package/rules/raw.js
When adding a Webpack rule, it's common to remove existing rules for that file type. For example, if you're adding a custom svg loader, you may want to exclude `.svg` from existing rules like so:
```
const fileLoaderRule = config.module.rules.find(rule => rule.test.test('.svg'));
fileLoaderRule.exclude = /\.svg$/;
```
The rules in shakapacker's wepback config used a mix of arrays and regular expressions, making this kind of iteration a pain to implement. These changes refactor all rules to use regular expressions to allow for easy customization.
=> Standardized Webpack rule formatting

CHANGELOG.md, README.md, lib/install/config/webpacker.yml, lib/install/template.rb, lib/webpacker/configuration.rb, lib/webpacker/railtie.rb, lib/webpacker/version_checker.rb, test/configuration_test.rb, test/fixtures/beta_package.json, test/fixtures/git_url_package.json, test/fixtures/github_url_package.json, test/fixtures/normal_package.json, test/fixtures/relative_path_package.json, test/fixtures/semver_caret_package.json, test/fixtures/semver_tilde_package.json, test/fixtures/without_package.json, test/test_app/config/webpacker.yml, test/version_checker_test.rb
Closes #36 
- Adds version check to ensure consistency between gem and npm package versions (mostly adapter from https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/version_checker.rb)
- Updates instructions and generators to use bundler `--strict` and yarn `--exact` flags to lock versions.
TODO:
=> Ensure consistent versions of package and gem

docs/v6_upgrade.md
These are some improvements based on what I've found when upgrading our applications to use `shakapacker`.
It's still not entirely accurate, but want to get the big ones out of the way since I'm still doing upgrades and editing via GitHub 😅 
Most of what was there was accurate, it just was presented as happening via `@rails/webpacker` when it actually happened via `shakapacker` (i.e., the bin scripts don't get renamed and the webpack config doesn't get merged into one)
=> docs: improve v6 upgrade guide

CHANGELOG.md, README.md, lib/install/config/webpacker.yml, lib/webpacker/dev_server.rb, lib/webpacker/instance.rb, package/inliningCss.js, test/webpacker_test.rb
This PR is for #68
This will cause style-loader to not be used if `inline_css: false` is set in the dev_server options. Any value other than `false` (including `nil`) will result in the current behavior.
I have a test for the `inlining_css?` method, and I did manually test that this has the desired effect in my own application, but I'm not sure how to best wire up a test for it otherwise.
=> Add support for disabling style-loader via inline_css: false.

CHANGELOG.md, lib/webpacker/dev_server.rb
Set the default webpack dev server connect timeout to 0.1s for calling the #running? method
Raised an issue and a PR was requested in #73 
Reproducing this issue is a little tricky as it means having a dev server that takes longer than 0.01s to accept a TCP connection. Perhaps it could be reproduced with a very busy workstation.
I have observed this happening repeatedly while troubleshooting with coworkers, but it doesn't typically happen for me, although I have also seen it. I am recommending this change because firstly, it has proved to be a more reliable value in my observations.
But also, the change from 1s to 0.01s seems to have been made without much discussion and without any stated reason:
rails/webpacker/pull/753
It is thankfully configurable now and we have done that for …
=> Increase default connect timeout to 0.1

docs/style_loader_vs_mini_css.md, lib/install/config/webpacker.yml
=> Add doc for differences between the CSS loader options

package/swc/index.js
move "loose" setting in swc config from under env to under jsc
matches the babel setting of the same name:
https://swc.rs/docs/configuration/compilation#jscloose
workaround for this:
https://github.com/swc-project/swc/issues/3943
also make the "coreJs" setting an integer which seems to be what the swc config schema validator wants
fixes #77
=> tweak swc config for parity with babel

CHANGELOG.md, lib/install/config/webpacker.yml, lib/webpacker/commands.rb, lib/webpacker/compiler.rb, lib/webpacker/configuration.rb, lib/webpacker/manifest.rb, package/__tests__/config.js, package/config.js, package/environments/base.js, test/configuration_test.rb, test/test_app/config/webpacker_manifest_path.yml
This is another run at the old https://github.com/rails/webpacker/pull/3152 PR
Unlike that PR, this version doesn't change the default behaviour at all - manifest.json will stay in public/packs, unless you set `manifest_path` in webpacker.yml.
WDYT?
=> Configurable manifest path

CHANGELOG.md, README.md, lib/webpacker/helper.rb, test/helper_test.rb
Previously discussed in #39 
This is necessary to allow usage like, eg:
```
<%= stylesheet_pack_tag :application %>
<%= stylesheet_pack_tag :print, media: "print" %>
```
However, it can result in duplicate style chunks on the page,
so the following should still be used where possible -
```
<%= stylesheet_pack_tag :application, :admin %>
```
=> Permit calling stylesheet_pack_tag more than once per page

docs/deployment.md
If "tmp/webpacker" is not listed here, assets will be compiled even if there are no changes in JavaScript or CSS.
=> Adding webpacker dir to linked_dir

CHANGELOG.md, lib/webpacker/configuration.rb, test/configuration_test.rb
Fixes #103.
See test run: https://github.com/shakacode/react_on_rails/runs/6036261442?check_suite_focus=true
https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/webpacker_utils.rb#L53-L55
refers to 
```ruby
Webpacker.config.public_manifest_path.exist?
```
We need to put back the method (maybe with a warning that it's deprecated and remove it for version 7?)
```
def public_manifest_path
manifest_path
end
```
=> Put back config.public_manifest_path

CHANGELOG.md, package/babel/preset.js
Fixes #106. This is a potentially breaking change for users who have coded around the loose mode behaviors already, so there should probably be a note in the release notes about how to get the original config back if you need to--essentially the workaround from #106, only in reverse:
```js
// babel.config.js
module.exports = function (api) {
// fetch the default babel config
const defaultConfigFunc = require("shakapacker/package/babel/preset.js");
const resultConfig = defaultConfigFunc(api);
// you can either re-enable "loose" mode to bring back the original behavior, or use "assumptions" 
// to manage which edge cases you are ignoring on a more fine-grain level. Enabling all assumptions
// is equivalent to turning "loose" mode back on.
// to enable "loose" mode, add "loose: true" to the …
```
=> Remove "loose" mode from the default babel configuration

Gemfile.lock, README.md, lib/webpacker/helper.rb, test/helper_test.rb
Another stab at improving #39 
Adds new helper to allow providing additional packs in addition that get appended to the main `javascript_pack_tag` call
`javascript_pack_tag` calls still raises when used multiple times but helper can streamline addition of packs in partials or conditionally.
Once we get list of all the tags to output, we deduplicate them and prioritise non-deferred ones - if particular bit is required by both deferred and non deferred call, the non-deferred one will be the one loaded.
Still needs testing and cleanup but just wanted to get initial version out to get thoughts and opinions
cc @justin808
=> append_javascript_pack_tag helper

README.md, lib/webpacker/compiler.rb, test/compiler_test.rb
Rather than calculating and storing digest for the assets, we can try and just check for the latest modified file in the paths we're watching.
This PR removes the digest calculation logic and instead finds and stores modified time of the last updated file. This is still stored in the cache directory after compilation and used for freshness comparison.
Would be great to have some bigger repo to benchmark, but on fairly small sized app, the timestamp is obviously much quicker than calculating digests. Both are reasonably quick but every little helps!
=> Use modified time rather than digest for freshness check

README.md, lib/install/config/webpacker.yml, lib/tasks/webpacker/clean.rake, lib/tasks/webpacker/clobber.rake, lib/tasks/webpacker/compile.rake, lib/webpacker/configuration.rb, test/configuration_test.rb, test/test_app/config/webpacker_no_precompile.yml
Enables the use of a webpacker.yml config value as a complement to `ENV["WEBPACKER_PRECOMPILE"]`
=> Add config.webpacker_precompile

README.md
Closes #88 
Adds a line to a readme about the effect of Rails public file server caching on shakapacker assets
=> Document effect of Rails caching on shakapacker assets

package.json
Bumping up the version for webpack-dev-server to 4.9.0 -- All known vulnerabilities have been eliminated in this version.
=> updated webpack-dev-server to 4.9.0

README.md, docs/react.md
Adds docs on React integration (as discussed [here](https://github.com/shakacode/shakapacker/issues/92#issuecomment-1101227999)).
=> Added documentation for React integration

CHANGELOG.md, package/rules/file.js
Do not use path.join because it introduces backslashes on Windows platforms. Fixes #114 .
=> Fix backslash in CSS urls on Windows

Gemfile, Gemfile.lock, package.json
the current version of nokogiri has a serious vulnerability and must be upgraded. 
https://nvd.nist.gov/vuln/detail/CVE-2022-29181
=> Updated Nokogiri gem to fix vulnerability

Gemfile.lock
Follow up from https://github.com/shakacode/shakapacker/pull/129
Adds additional platforms so native Nokogiri platform can be pulled in if applicable
=> Add additional platforms to Gemfile lock

CHANGELOG.md, lib/tasks/webpacker/compile.rake, lib/tasks/webpacker/yarn_install.rake, lib/tasks/yarn.rake
Restores behaviour removed in #131 and adds deprecation notice as we should only remove this in Shakapacker v7
=> Bring back automatic yarn install run with deprecation notice

CHANGELOG.md, package/rules/erb.js
Fixes #137 
Reference https://github.com/usabilityhub/rails-erb-loader/issues/63
Running `rails-erb-loader` through runner with spring enabled is likely to cause random issues and failures. This will now pass `DISABLE_SPRING` env to runner explicitly in order to skip Spring being used
=> Don't run Spring in erb loader

README.md, lib/webpacker/helper.rb, test/helper_test.rb
To add stylesheets for the new filesystem-based Component Registry API, We need a stylesheet to append helper. This PR Adds the` stylesheet_append_tag` helper to Shakapacker Codebase
=> Add Append StyleSheet Pack Tag Helper

CHANGELOG.md
This PR just adds Changelog Text for `append_stylesheet_pack_tag` added in https://github.com/shakacode/shakapacker/pull/144
=> Add Changelog for `append_stylesheet_pack_tag` helper

CHANGELOG.md, README.md, lib/webpacker/helper.rb, test/helper_test.rb
This PR Addresses Docs, Error Messages and Changelogs-related Issues reported by @justin808 in https://github.com/shakacode/shakapacker/pull/152 and https://github.com/shakacode/shakapacker/pull/152
=> Update Changelog, Docs and Error Message

CHANGELOG.md, lib/webpacker/compiler.rb
When rails tests are run in parallel, multiple `webpack` compilations are kicked off at the same time.
This is _really_ resource intensive and slow.
For example, with 4 workers, `rails test:system` starts 4 webpack compilations:
Before:
After:
=> Only compile if no compilation is currently already in progress

CHANGELOG.md, lib/webpacker/helper.rb
Return nil from `append_*` helpers so it does not matter whether one
uses `<%= … %>` or `<% … %>` ERB syntax.
Fixes #119
=> Prevent rendering queue into view when using wrong syntax

CHANGELOG.md, lib/webpacker/configuration.rb, test/configuration_test.rb
React on Rails requires access to the `nested_entries` shakapacker configuration for file-system-based automated bundle generation feature to handle misc edge-cases. This PR adds an accessor method for the `nested_entries` attribute.
=> Add accessor method for `nested_entries`

CHANGELOG.md, README.md, lib/install/bin/webpacker, lib/install/bin/webpacker-dev-server, lib/webpacker/runner.rb
changed NODE_ENV defaults from
```ruby
ENV["NODE_ENV"]  ||= ENV["RAILS_ENV"]
```
to
```ruby
ENV['NODE_ENV'] ||= (ENV['RAILS_ENV'] == production) ? 'production' : 'development'
```
=> Change NODE_ENV defaults

CHANGELOG.md, lib/install/config/webpacker.yml, package/environments/__tests__/base.js, package/environments/base.js, test/test_app/config/webpacker_css_extract_ignore_order_warnings.yml
While using a File-System-based automated bundle generation feature, miscellaneous warnings suggesting css order conflicts were encountered due to the `mini-css-extract-plugin.` This PR mutes those warnings by using the `ignoreOrder` flag which can be configured using `css_extract_ignore_order_warnings` flag in `webpacker.yml`
- Topological Ordering of Packs when loaded using `append_stylesheet_pack_tag` and `stylesheet_pack_tag`
- Re-order CSS imports
- Removal of CSS imports as globals.
- Debug Components usage and import order.
For projects where CSS order has not been mitigated through consistent use of scoping or naming conventions, the CSS order warnings are essential and may result in visual differences.
=> Fix Module Order Warnings for Projects using Mini-Css-Extract-Plugin

package/environments/base.js
It will cause below error if not removed.
```log
─▪ bin/webpacker-dev-server 
[webpack-cli] Failed to load '/Users/guochunzhong/git/shin/pagila-rails-portal/config/webpack/webpack.config.js' config
[webpack-cli] Invalid options object. Mini CSS Extract Plugin has been initialized using an options object that does not match the API schema.
- options.chunkFilename should be one of these:
non-empty string | function
-> This option determines the name of non-entry chunk files.
-> Read more at https://github.com/webpack-contrib/mini-css-extract-plugin#chunkfilename
Details:
* options.chunkFilename should be a non-empty string.
* options.chunkFilename should be an instance of function.
```
=> Remove #192 introduce extra split() call.

CHANGELOG.md, docs/style_loader_vs_mini_css.md, lib/install/config/webpacker.yml
The docs and comments use "mini-extract-css-plugin" name sometimes where "mini-css-extract-plugin" was meant. This fixes these four places.
I know it's nitpicky, but it actually lands in generated `webpacker.yml` and I was confused for a moment why I cannot install `mini-extract-css-plugin` because it does not exist (opens a possibility of name squatting as well).
=> Use correct name of mini-css-extract-plugin

CHANGELOG.md, package.json
Keep using babel-loader 8.x for development to avoid dropping support for Node 12
Close #196
---
I've tested with a local application by running `npm pack` and referencing shakapacker as `"file:../shakapacker/shakapacker-6.5.4.tgz"` in `package.json`. I'm not a javascript developer, so I may miss something important, please double check
=> Allow babel-loader 9.x

docs/v6_upgrade.md
I don't understand why we're mentioning `shakapacker` in the instructions to upgrade from Webpacker v5 to Webpacker v6 RC.
=> Update upgrade documentation

lib/install/template.rb
Since CSP file (`config/content_security_policy.rb`) format has changed in Rails 7, shakapacker generator on `webpacker:install` causes a warning mentioned in #221. Also it seems we don't need to modify this file in Rails 7.
closes #221
Warning: Since we don't cover Rails 7 in our CI, this PR doesn't have proper test.
=> Remove unneeded code related to CSP config 

.github/workflows/ruby.yml
Set Rubygems to use version 3.3.13 in CI.
It seems our test for edge version of Rails causes this issue. Rails 7.1.0-alpha depends on Rubygems 3.3.13 and since this version is not installed by default, we get into such a break.
More info: https://github.com/rails/rails/commit/3aa32f2176389d563deff0c799198378666d9f17
=> Fix broken CI due to version of Rubygems

CONTRIBUTING.md
Since we close non-critical issues to maintain focus on critical ones, I added a link to the closed issues with "help wanted" label.
I have also added a table of content to make it easier to see all the sections of the guideline at a glance.
=> Update CONTRIBUING guideline and add link to closed issues

CHANGELOG.md, lib/install/template.rb
Due to different content of `bin/setup` in different Rails versions, the earlier version of the generator couldn't modify this file properly in all circumstances.
This commit handles the following scenarios:
- If there is a commented line for `system('bin/yarn')`, uncomment it.
- Otherwise, regardless of using single or double quotations in different Rails versions, add `system! 'bin/yarn'` after the intended line.
I have manually checked the impact of this PR on the following Rails versions:
- `5.2.8`: where we already have commented `system('bin/yarn')`
- `6.1.7`: where we have `system('bundle check') || system!('bundle install')`
- `7.0.4`: where we have `system("bundle check") || system!("bundle install")`
closes #226
=> Fix bin/setup modification failure in installation

CHANGELOG.md, package.json, package/rules/__tests__/__utils__/webpack.js, package/rules/__tests__/babel.js, package/rules/__tests__/esbuild.js, package/rules/__tests__/index.js, package/rules/__tests__/swc.js, package/rules/babel.js, package/rules/esbuild.js, package/rules/jscommon.js, package/rules/swc.js, yarn.lock
In specific scenarios, you would need to transpile some of `node_modules`. This addition allows to specify `node_modules` to include via `webpacker.yml => additional_paths` configuration.
closes #208
=> fixed babel configuration for #208

docs/v6_upgrade.md
Add anchor to the "follow the steps below", as the most intuitive interpretation is that the steps below refer to the instructions directly below, when in reality, it meant "the next section".
_(Spent an entire afternoon to find out that the instructions were really in the next section, and had to undo everything)_
=> [Minor] Update v6_upgrade.md

CHANGELOG.md
v6.5.6 appeared twice, with different release dates. Consolidated them under the correct release date based on RubyGems
=> Fix duplicate CHANGELOG entries

lib/webpacker/instance.rb, spec/webpacker_spec.rb
While working on implementing shakapacker to Decidim, i have came across a small issue that prevented me to continue upgrading.
At Decidim we have a runtime that allows us to inject paths dynamically to webpacker config, saving a new YAML file in the app's tmp folder. Unfortunately neither webpack, nor Shakapacker allows dynamic configuration. 
The functionality has implemented a while back in Webpacker  via [#2990](https://github.com/rails/webpacker/pull/2990), yet the Rails app is reading the default config. As running in Rails context, the`Webpacker.config` always returns the full path of `config/webpacker.yml`
Relevant files from #2990
https://github.com/shakacode/shakapacker/blob/4c92e2a956c443233a6f00b65df7db67b5cfb2ba/lib/webpacker/runner.rb#L12-L15
=> Allow configuration of webpacker.yml through env variable

README.md
[Closes #264]
The [turbolinks](https://github.com/turbolinks/turbolinks) project isn't maintained anymore, so the docs needed updating to refer to refer to `@hotwired/turbo-rails` instead: https://github.com/hotwired/turbo-rails
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by `~`._
_Add the CHANGELOG entry at the top of the file._
N/A
=> [Docs] Update turbolinks references to turbo

lib/shakapacker/runner.rb
Fix backward compatibility for setting WEBPACKER_CONFIG in webpack.config.js. This issue was seen in HiChee.
=> Fix backward compatibility for setting WEBPACKER_CONFIG in webpack.config.js

CHANGELOG.md, package/babel/preset.js
Fixes #267 
I was thinking of doing something similar to SWC rules https://github.com/shakacode/shakapacker/blob/master/package/swc/index.js#L28-L33 but in the end decided it brings no value realistically.
The setting in SWC to figure out config from the file was added to go around the limitations there, Babel should be already correctly figuring out file types and behaviour from the extensions with the default preset settings.
_Remove this line after checking all the items here. If the item is not applicable to the PR, both check it out and wrap it by 
_Add the CHANGELOG entry at the top of the file._
=> Remove @babel/preset-typescript defaults

CHANGELOG.md, lib/tasks/shakapacker/compile.rake
As per comments in the source code, we drop the feature to add `yarn:install` rake task.
---
Related Issue #237
Related PR #238
=> Remove redundant code for enhancing precompile task

CHANGELOG.md, lib/webpacker/compiler.rb
Fixes #158 
Potentially addresses #269 ?
Moves `shakapacker.lock` file from system tmp dir into project tmp directory.
=> Move compilation lock file into the working directory

CHANGELOG.md, package/utils/get_style_rule.js
Set CSS modules mode to `icss` if a style file is not a module, `local` otherwise. It allows using `ICSS` features such as `:import` and `:export` without using further `CSS Module` functionality. ICSS features were applied by default to all files before `css-loader@v4`, but it's been changed in the next versions. (Please refer to `css-loader` [example](https://github.com/webpack-contrib/css-loader#separating-interoperable-css-only-and-css-module-features))
=> Set CSS modules mode depending on file type

CHANGELOG.md, lib/install/config/shakapacker.yml, lib/shakapacker/dev_server.rb, lib/shakapacker/dev_server_proxy.rb, lib/shakapacker/dev_server_runner.rb, package/dev_server.js, package/environments/development.js, spec/dev_server_spec.rb, spec/test_app/config/shakapacker.yml
This PR adds/modifies the dev-server config based on the standard Webpack dev-server configuration.
closes #217
=> Update webpack dev server configuration

docs/v6_upgrade.md
Since `v6.0.0-rc.7` (https://github.com/shakacode/shakapacker/commit/b64434d784257cb9c9b40969d17ac0aa3dc6e73d) the static file path has been updated from `media/` to `static/`, added update instructions to `docs/v6_upgrade.md`.
_Add the CHANGELOG entry at the top of the file._~
=> Add update instructions to `docs/v6_upgrade.md` for `asset_pack_path`

CHANGELOG.md, package/rules/__tests__/file.js, package/rules/file.js
Fixes https://github.com/shakacode/shakapacker/issues/177
When generating file paths for static assets, a top level directory will no longer be stripped. Fixes also previously broken output of the files referenced from top level of the source directory and adds relevant tests.
This is a breaking change so best suited for v7 release
=> Stop stripping top level dirs

CHANGELOG.md, lib/install/config/shakapacker.yml, lib/shakapacker/configuration.rb, spec/configuration_spec.rb
- Set `source_entry_path` to `packs` by default.
- Process `source_entry_path` as a relative path to `source_path`, allowing to accept values starting with '/'.
- Set `nested_entry` to `true` by default.
For additional discussion, check the old PR: #205 
Closes #204
=> Improve source_entry_path robustness

CHANGELOG.md, lib/shakapacker/configuration.rb
Remove the deprecated method `check_yarn_integrity` from `Shakapacker::Configuration`.
=> Remove check_yarn_integrity method

lib/tasks/shakapacker/check_binstubs.rake, spec/shakapacker/rake_tasks_spec.rb
Because of exiting from `shakapacker:check_binstubs`, `shakapacker:verify_install` couldn't pass. As a result, `shakapacker:compile` couldn't be added to `assets:precompile` task.
This PR should resolve and close #305 issue.
=> Fix check binstubs task by removing exit

CHANGELOG.md, lib/install/template.rb
Our installation code couldn't detect the right version for installing the npm package if we were on an RC version and as a result, it was trying to install the `next` version which is currently set to `v6.0.0-rc.14`. This PR fixes this issue.
=> Fix detection of version for npm during installation

CHANGELOG.md, README.md, lib/install/binstubs.rb, lib/install/template.rb
Adding a feature to use `FORCE=true` env variable to force overriding files during installation. Besides making it easier to install, this feature is particularly needed for #300.
=> Add feature to force override in installation

CHANGELOG.md, lib/install/template.rb
Currently, we add Shakapacker peer dependencies as dependencies in `shakapacker:install` task. This results in failure in adding `webpack-dev-server` to devDepenencies.
This PR fixes this issue issue.
_Add the CHANGELOG entry at the top of the file._
=> Improve handling devDependencies in installation

docs/v7_upgrade.md
This PR updates v7 upgrade guide by adding a section related to changes in the static assets path.
Closes #319
=> Update v7 upgrade guide for static assets path

CHANGELOG.md, lib/tasks/shakapacker/compile.rake
This PR brings back the logic for creating `assets:precompile` if it is missing.
Fixes #323
=> Fix missing assets:precompile task

CHANGELOG.md, lib/shakapacker/compiler.rb, lib/shakapacker/utils/misc.rb, lib/tasks/shakapacker/binstubs.rake, lib/tasks/shakapacker/install.rake, spec/generator_specs/generator_spec.rb
Hello, when upgrading my app from v6 to v7, I noticed some commands are failing because I have a space in the absolute path of my project.
=> Support spaces in app path

.github/workflows/dummy.yml, .github/workflows/generator.yml, .github/workflows/jest.yml, .github/workflows/js-lint.yml, .github/workflows/rubocop.yml, .github/workflows/ruby-backward-compatibility.yml, .github/workflows/ruby.yml
To run CI on PR made by contributors other than the official team, we need to include `pull_request` in the list of triggers.
=> Include PR as a trigger for CI

docs/v7_upgrade.md
The function _generateWebpackConfig_ was misspelled as _generate**d**WebpackConfig_, which could cause build issues if someone copy-and-paste the function name from the docs.
Fixes #335.
=> Fix typo in v7 upgrade guide

package.json, package/index.d.ts
This adds types to the npm package to allow using it in TypeScript-based files. This is effectively a port of https://github.com/ackama/rails-template/blob/main/variants/frontend-base-typescript/types.d.ts#L1-L21 (+ the changes for v7).
This is meant to be a starting point rather than completely type everything because once this is landed it should be very easier for the types of other functions and properties be added, whereas I don't have the bandwidth to pin down the exact types for everything.
I have tested this works by generating a new Rails project from our template, and then replacing the lines linked to above in `types.d.ts` with this change to `node_modules/shakapacker` and then running `typecheck`.
_Remove this line after checking all the items here. If the item does not apply …
=> feat: add types for npm package

lib/shakapacker/version_checker.rb, spec/fixtures/beta_pnpm-lock.v7.yaml, spec/fixtures/beta_pnpm-lock.v8.yaml, spec/fixtures/git_url_pnpm-lock.v7.yaml, spec/fixtures/git_url_pnpm-lock.v8.yaml, spec/fixtures/github_url_pnpm-lock.v7.yaml, spec/fixtures/github_url_pnpm-lock.v8.yaml, spec/fixtures/relative_path_pnpm-lock.v7.yaml, spec/fixtures/relative_path_pnpm-lock.v8.yaml, spec/fixtures/semver_caret_pnpm-lock.v7.yaml, spec/fixtures/semver_caret_pnpm-lock.v8.yaml, spec/fixtures/semver_exact_pnpm-lock.v7.yaml, spec/fixtures/semver_exact_pnpm-lock.v8.yaml, spec/fixtures/semver_tilde_pnpm-lock.v7.yaml, spec/fixtures/semver_tilde_pnpm-lock.v8.yaml, spec/fixtures/without_pnpm-lock.v7.yaml, spec/fixtures/without_pnpm-lock.v8.yaml, spec/shakapacker/version_checker_spec.rb
Adds support for determining the version of Shakapacker being installed when `pnpm` is the package manager; while that is not officially supported by Shakapacker (yet 🤞), given this is stable and small I think its worth landing ahead of #349.
Pulled from #349
=> feat: add support for determining Shakapacker version via `pnpm-lock.yaml`

CHANGELOG.md, lib/shakapacker/dev_server_runner.rb, lib/shakapacker/webpack_runner.rb
Currently debugging options for `node` are handled by switching to calling `node` which is fine except requires the absolute path to the javascript file to execute to be passed which isn't what happens if `node_modules_bin_exist?` is false because that falls back to just `yarn webpack` and `yarn webpack serve`:
```
cmd = if node_modules_bin_exist?
["#{@node_modules_bin_path}/webpack", "serve"]
else
["yarn", "webpack", "serve"]
end
```
This switches to providing those options using the [`NODE_OPTIONS`](https://nodejs.org/api/cli.html#node_optionsoptions) env variable instead, which should ensure the options are always enabled regardless of how the desired commands are invoked.
This change also makes #349 / #195 a little easier.
I have tested this locally using …
=> fix: use `NODE_OPTIONS` instead of calling `node` directly for debugging

.github/workflows/ruby.yml
#299 mistakenly changed the `ruby` workflow to run the backwards compatible specs, meaning they were being run twice and the `shakapacker` specs were never being run.
=> ci: actually run shakapacker specs

.github/workflows/dummy.yml, .github/workflows/generator.yml, .github/workflows/jest.yml, .github/workflows/js-lint.yml, .github/workflows/rubocop.yml, .github/workflows/ruby-backward-compatibility.yml, .github/workflows/ruby.yml
Disabling persisted credentials is a nice-to-have security improvement - it's very unlikely to ever actually be exploitable for this codebase, but might as well disable it nonetheless; see https://github.com/actions/checkout/issues/485 for more.
=> ci: update actions and disable persisted git credentials

spec/backward_compatibility_specs/compiler_strategy_spec.rb, spec/backward_compatibility_specs/configuration_spec.rb, spec/backward_compatibility_specs/dev_server_runner_spec.rb, spec/backward_compatibility_specs/dev_server_spec.rb, spec/backward_compatibility_specs/digest_strategy_spec.rb, spec/backward_compatibility_specs/engine_rake_tasks_spec.rb, spec/backward_compatibility_specs/helper_spec.rb, spec/backward_compatibility_specs/instance_spec.rb, spec/backward_compatibility_specs/manifest_spec.rb, spec/backward_compatibility_specs/mtime_strategy_spec.rb, spec/backward_compatibility_specs/rake_tasks_spec.rb, spec/backward_compatibility_specs/webpack_runner_spec.rb, spec/generator_specs/generator_spec.rb, spec/shakapacker/compiler_strategy_spec.rb, spec/shakapacker/configuration_spec.rb, spec/shakapacker/dev_server_runner_spec.rb, spec/shakapacker/dev_server_spec.rb, spec/shakapacker/digest_strategy_spec.rb, spec/shakapacker/engine_rake_tasks_spec.rb, spec/shakapacker/helper_spec.rb, spec/shakapacker/instance_spec.rb, spec/shakapacker/manifest_spec.rb, spec/shakapacker/mtime_strategy_spec.rb, spec/shakapacker/rake_tasks_spec.rb, spec/shakapacker/shakapacker_spec.rb, spec/shakapacker/version_checker_spec.rb, spec/shakapacker/webpack_runner_spec.rb
This:
* improves the overall grammar of a lot of the example titles
* including a spelling mistake of my own, and replacing "throws" with "raises" as I find that to more idiomatic in Ruby
* makes the layout more consistent by adding a newline before the assertion in a lot of cases
* imo this reads better, and it is also consistent with some of the existing examples
* making the specs more consistent with each other and the backward compatible specs
=> test: improve consistency of example names and general layout

CHANGELOG.md, README.md, docs/troubleshooting.md, docs/using_esbuild_loader.md, package/__tests__/index.js, package/index.d.ts, package/index.js, spec/dummy/config/webpack/commonWebpackConfig.js
Enables providing `generateWebpackConfig` an optional object that is included in the config merge, reducing the amount of boilerplate code you have to write when doing basic customization to the config.
Resolves #329
=> feat: support passing config to `generateWebpackConfig` for merging

CHANGELOG.md, lib/install/template.rb
`shakapaker.yml` has `source_entry_path: packs` instead of `/` by default.
I've just bootstraped a new project and installed shakapacker. The default install yields `Shakapacker::Manifest::MissingEntryError` because `application.js` is put in `app/javascript/` instead of `app/javascript/pack/`.
=> install: add the boilplate application.js into packs/

lib/shakapacker/deprecation_helper.rb
Correct the v7 upgrade guide URL in the deprecation message
Closes #358
=> Fix the guide url in deprecation message

lib/shakapacker/compiler.rb, lib/shakapacker/configuration.rb, spec/shakapacker/compiler_spec.rb, spec/shakapacker/configuration_spec.rb, spec/shakapacker/spec_helper_initializer.rb
A step towards moving configurations into the Configuration class.
This PR is required to be merged so that #364 can proceed.
This PR changes the internal functionalities. No docs or changelog is required.
=> Move compiler configuration into configuration class

spec/backward_compatibility_specs/dev_server_runner_spec.rb, spec/shakapacker/dev_server_runner_spec.rb
Currently some of the tests are not being run as their assertion code just isn't being called - from what I can tell, I don't think RSpec has ever supported passing a block to `receive` in a way that gets executed (except maybe if the mocked method actually expects a block but I've not tested that).
This does reveal some interesting behaviour with the `https` logic that is probably worth addressing:
1. determining if `https` is being used is based on checking the `protocol` but there's an `https?` method too - it looks like this generally just has not been deprecated properly
2. the runner errors if `--https` is provided but `https` isn't enabled but it doesn't …
=> test: properly verify dev server exec

.github/workflows/dummy.yml, spec/dummy/Gemfile
This functionality is now built into `selenium-webdriver` and the two can conflict
=> test: remove `webdrivers` gem from dummy app

CHANGELOG.md, lib/shakapacker/dev_server_runner.rb
`https: true` has been deprecated in favor of `server: 'https'`
=> fix: don't recommend deprecated `https` config option

spec/dummy/package.json
Yarn v1.22.20 introduced a check [to ensure that the right version of Yarn was actually being used](https://github.com/yarnpkg/yarn/releases/tag/v1.22.20), which breaks the specs because while the dummy app specifies it should be using Yarn v3 in it's `package.json`, Yarn Berry is not properly setup so it'll never get used.
Removing `packageManager` resolves this.
=> test: remove `packageManager` from dummy app

CHANGELOG.md, lib/install/config/shakapacker.yml, lib/shakapacker/dev_server.rb
If this flag is deprecated then it shouldn't be mentioned in the generated config because that just encourages its usage; we should also be omitting a deprecation warning so people know to move off it
=> fix: emit a deprecation warning for `https` and don't mention it in generated config

CHANGELOG.md, lib/shakapacker/dev_server_runner.rb, spec/shakapacker/dev_server_runner_spec.rb
Webpack `devServer.hot` property can be set to the string `only` if you don't want an automatic refresh of the page it the update isn't accepted.
https://webpack.js.org/configuration/dev-server/#devserverhot
This PR adds support for that setting in `shakapacker.yml`.
I tried adding tests, but changing e.g.
https://github.com/shakacode/shakapacker/blob/c78a5c032f9b654dcd3151a3dfb5a1359187bc88/spec/shakapacker/dev_server_runner_spec.rb#L58
to `verify_command(cmd, argv: (["--nope, not here"]))` does not fail the test - it still passes. So I'm not sure how to test it 😅 
It does _work_ though - I've verified in my own project.
=> feat: pass through `hot: only` to `webpack-dev-server`

docs/v6_upgrade.md
Having `master` at the end of the git comparison makes the example link nearly worthless now & increasingly worthless as more commits are added, so we should restrict the commit range of the comparison to only include relevant changes.
=> Restrict commit range of comparison

CHANGELOG.md, lib/shakapacker/dev_server_runner.rb, spec/backward_compatibility_specs/dev_server_runner_spec.rb, spec/backward_compatibility_specs/webpacker_test_app/config/webpacker.yml, spec/backward_compatibility_specs/webpacker_test_app/config/webpacker_other_location.yml, spec/shakapacker/dev_server_runner_spec.rb, spec/shakapacker/test_app/config/shakapacker.yml, spec/shakapacker/test_app/config/shakapacker_other_location.yml
webpacker-dev-server >= 4 enables HMR by default, so explicitly disable when `hmr: false`. Fixes #390
=> fix: `hmr: false` doesn't disable Hot Module Replacement

CHANGELOG.md, lib/shakapacker/configuration.rb, spec/shakapacker/configuration_spec.rb
Show deprecation message for `relative_url_root` only if it is used.
Fixes #399
=> Show deprecation message for relative_url_root only if used

.github/workflows/dummy.yml, .github/workflows/generator.yml, .github/workflows/jest.yml, .github/workflows/js-lint.yml, .github/workflows/rubocop.yml, .github/workflows/ruby-backward-compatibility.yml, .github/workflows/ruby.yml, CHANGELOG.md, docs/react.md, docs/v6_upgrade.md, lib/shakapacker/deprecation_helper.rb, lib/shakapacker/helper.rb, package/index.js, spec/backward_compatibility_specs/helper_spec.rb, spec/fixtures/github_url_package-lock.v1.json, spec/fixtures/github_url_package-lock.v2.json, spec/fixtures/github_url_package.json, spec/fixtures/github_url_pnpm-lock.v7.yaml, spec/fixtures/github_url_pnpm-lock.v8.yaml, spec/fixtures/github_url_yarn.v1.lock, spec/fixtures/github_url_yarn.v2.lock, spec/shakapacker/helper_spec.rb, spec/shakapacker/version_checker_spec.rb
This is the canonical default branch these days; once this is merged ideally the `master` branch should be renamed to `main` using GitHub's UI so that workflow runs and other such logs are retained.
I've also snuck in adding `next` to the list of branches to run CI on.
=> ci: switch to `main` and run on `next` branch too

lib/shakapacker/compiler.rb
By default Webpack use stderr: https://webpack.js.org/configuration/other-options/#stream so Webpack plugins messages end up with`error` severity. 
For example: https://github.com/gregnb/filemanager-webpack-plugin/blob/master/src/actions/copy.js#L25
Thank you!
=> Emit warnings instead of errors when compilation is success but stderr is not empty

CHANGELOG.md, package.json
This was released a few hours ago, and is needed to patch a vulnerability.
~This looks to be working fine out of the box for me, though I'll do a look through the actual changelog later to determine if there's any followup work; would be good to get this released in the meantime though.~ looks like they just removed a bunch of previously deprecated stuff; my CSP is broken for some reason but that isn't Shakapackers problem
=> fix: allow `webpack-dev-server` v5

.github/workflows/generator.yml, .github/workflows/ruby.yml, .rubocop.yml, CHANGELOG.md, README.md, shakapacker.gemspec
This isn't to say we won't drop support for other versions of Ruby, but we should definitely drop support for 2.6.
I have realised CI isn't covering newer versions of Ruby, but I'll do a dedicated PR adding those.
=> feat!: drop support for Ruby 2.6

CHANGELOG.md, lib/shakapacker/dev_server.rb, spec/dummy/config/shakapacker.yml, spec/mounted_app/test/dummy/config/webpacker.yml, spec/shakapacker/dev_server_spec.rb, spec/shakapacker/shakapacker_spec.rb, spec/shakapacker/test_app/config/shakapacker_css_extract_ignore_order_warnings.yml, spec/shakapacker/test_app/config/shakapacker_manifest_path.yml, spec/shakapacker/test_app/config/shakapacker_nested_entries.yml, spec/shakapacker/test_app/config/shakapacker_other_location.yml
This'll be a draft until #411 is landed on `master` and then `next` is rebased.
---
Time to axe this...
=> feat!: remove `https` option

.github/workflows/generator.yml, .github/workflows/node.yml, .github/workflows/ruby.yml
These are the newest LTS versions available
We should also test against Rails 7.1 but that's a bit more work to setup so will do that in another PR
(I also don't think we need to be running rubocop on each version of Ruby, but will check that later too)
=> ci: test against Ruby 3.1 and 3.2, and Node 20

.github/workflows/ruby.yml
We don't need to be running Rubocop on every version of Ruby as we've got `TargetRubyVersion` set which ensures we don't use syntax that isn't supported in 2.7.
=> ci: only run Rubocop with latest Ruby

CHANGELOG.md, package/__tests__/development.js, package/__tests__/production.js, package/__tests__/staging.js, package/__tests__/test.js, package/index.d.ts, package/index.js, spec/dummy/config/webpack/commonWebpackConfig.js
This was deprecated in v7 in favor of `generateWebpackConfig`, so now we can remove it
=> feat!: remove `globalMutableWebpackConfig`

.github/workflows/dummy.yml, .github/workflows/generator.yml, .github/workflows/node.yml, .github/workflows/ruby.yml
This should halve the number of jobs being run on `next` without losing anything so long as we continue to have a PR to `main` as that will trigger the workflows due to being a `pull_request`.
=> ci: don't run on pushes to `next`

.github/workflows/generator.yml
This might improve speed a little, but either way we don't seem to need to use this specific version of bundler anymore so lets just let `setup-ruby` manage it.
=> ci: use latest bundler in generator jobs

CHANGELOG.md, lib/install/config/shakapacker.yml, lib/shakapacker/version_checker.rb, spec/dummy/yarn.lock, spec/shakapacker/configuration_spec.rb, spec/shakapacker/version_checker_spec.rb
Per the current messaging, we want this to be the default in the new major.
=> feat!: enable `ensure_consistent_versioning` by default

CHANGELOG.md, package.json, package/environments/base.js, yarn.lock
Closes #384 and supersedes #388
Ref thread here https://github.com/shakacode/shakapacker/pull/388
Removes `glob` dependency that was only used in a single place - fetching entrypoints.
Rewrites getting entrypoint files using native `fs` module functions.
Tested running through test suite and veryfing the new function results in exactly same result as previous glob call
=> Remove dependency on glob

CHANGELOG.md, lib/shakapacker/compiler.rb, lib/shakapacker/configuration.rb, lib/shakapacker/env.rb, lib/shakapacker/instance.rb, spec/shakapacker/instance_spec.rb
Whilst investigating https://github.com/shakacode/shakapacker/issues/408 I couldn't quite replicate the issues but did notice there a few places in the code where we were not respecting `SHAKAPACKER_CONFIG` env variable. This moves it up one level to main `Shakapacker::Instance` so it should be used consistently.
There are places like runners where we were using configuration object directly but they were already accounting for path set by env variable.
=> Pass in shakapacker config consistently

package/rules/__tests__/file.js, package/rules/file.js
Follow up to #403
This test seems a little silly, but I don't think it's entirely unreasonable in the real world
=> fix: only strip paths that start with source path

README.md
The configuration change example is broken.
`const svgRule = config.module.rules.find(rule => rule.test.test('.svg'));` only works if `rule.test` is a RegExp (because of the call to `rule.test.test`).
`svgRule.test = svgRule.test.filter(t => !t.test('.svg'))` only works if `svgRule.test` is an array (because of the call to `svgRule.test.filter`).
My guess is that this error was introduced because [the same commit that created this example also changed that asset file's rule.test from arrays of RegExp to a single RegExp with conditional logic](https://github.com/shakacode/shakapacker/commit/c5257b13f1b58aa3d6a69e4ffff7ed55f3fb1f11).
This PR addresses that & also slightly expands on possible rule changes.
For even more possible configuration change logic, see #453
=> Update outdated webpack configuration example

spec/shakapacker/compiler_spec.rb
I'm not sure why CI has suddenly started failing but hopefully this'll fix it - I assume some dependency was requiring `ostruct` for us which has now changed.
=> test: require `ostruct` explicitly

.github/workflows/node.yml
As with #438, we don't need to run ESLint on every version of Node as tests will catch if we're not compatible.
=> ci: only run ESLint with latest Node

spec/dummy/yarn.lock
Fixes dummy specs fail because of Shakapacker version mismatch https://github.com/shakacode/shakapacker/actions/runs/8995105572/job/24709542960#step:6:186
=> Fix yarn.lock version in the dummy spec directory

CHANGELOG.md
=> Update CHANGELOG for version 8.4.0
