CHANGELOG.md
docs/v6_upgrade.md
lib/webpacker/compiler.rb

See https://github.com/rails/webpacker/pull/3233
Based on PR https://github.com/rails/webpacker/pull/3218
I detected the issue with #3218 when I noticed the timing was impossibly fast
Note, this method is still crazy slow on big projects. 
On a big project:
user     system      total        real
1.985895   2.741152   4.727047 (  9.214857)

Make watched_files_digest thread safe

---

README.md
docs/customizing_babel_config.md
docs/developing_webpacker.md
docs/troubleshooting.md
docs/v6_upgrade.md
lib/install/config/webpack/webpack.config.js
lib/install/package.json
lib/install/template.rb
lib/tasks/webpacker/info.rake
package.json
package/babel/preset.js
test/mounted_app/test/dummy/package.json
webpacker.gemspec

rails/webpacker ==> shakacode/webpackr

rename for webpackr

---

README.md
docs/customizing_babel_config.md
docs/developing_webpacker.md
docs/troubleshooting.md
docs/v6_upgrade.md
lib/install/config/webpack/webpack.config.js
lib/install/package.json
lib/install/template.rb
lib/shakapacker.rb
lib/tasks/webpacker/info.rake
package.json
package/babel/preset.js
test/mounted_app/test/dummy/package.json

Changed package name to `shakapacker` from @shakacode/shakapacker.

Remove namespace for npm, fix need to require 'webpacker'

---

README.md

[ci skip]
My editor was automatically doing these changes

Remove trailing whitespaces

---

lib/webpacker/compiler.rb

These commands have been renamed in https://github.com/rails/webpacker/pull/3252.

Fix command name in warning

---

docs/using_swc_loader.md

Fix syntax highlight

---

CHANGELOG.md
Gemfile.lock
docs/using_swc_loader.md

- Add changelog entry for SWC loader setup
- Add a note about API and config of SWC integration being subject to change
- Fix the `unreleased` compare link in changelog

Add changelog entry, update SWC usage docs

---

CHANGELOG.md
README.md
docs/using_esbuild_loader.md
lib/install/config/webpacker.yml
package.json
package/esbuild/index.js
package/rules/esbuild.js
package/rules/index.js
yarn.lock

Closes #29 
As expected, trivial implementation and works fairly well!

Enable esbuild-loader support

---

docs/v6_upgrade.md

Fix markdown indentation for ordered list.
Before
After

Fix markdown indentation

---

docs/v6_upgrade.md

A very small fix for v6_upgrade.md

Fix typos for v6_upgrade.md

---

package/inliningCss.js

Needs to use snake case even in js.
Didn't see a super easy way to add test coverage for this but happy to try

fix inline css config option

---

lib/webpacker/configuration.rb

Fixes https://github.com/shakacode/shakapacker/issues/123.

Don't enhance precompile if no config

---

CHANGELOG.md
lib/webpacker.rb
lib/webpacker/configuration.rb
lib/webpacker/env.rb
test/configuration_test.rb
test/env_test.rb
test/test_app/config/webpacker_defaults_fallback.yml

For custom environments fall back to production defaults

---

lib/install/bin/webpacker
lib/install/bin/webpacker-dev-server

BUNDLE_GEMFILE should be set before requiring bundler. Also minor cosmetic change.
```
File.expand_path("../../Gemfile", Pathname.new(__FILE__).realpath) =>
File.expand_path("../../Gemfile", __FILE__)
```

Set BUNDLE_GEMFILE before requiring bundler

---

test/version_checker_test.rb

Suppress a warning while executing tests
Close #211

Add underscore prefix to unused variables

---

package.json

Close #209
---
I've tested with a local application by running `npm pack` and referencing shakapacker as `"file:../shakapacker/shakapacker-6.5.4.tgz"` in `package.json`. I'm not a javascript developer, so I may miss something important, please double check

Allow webpack-cli 5.x

---

CHANGELOG.md
lib/install/config/webpacker.yml
test/mounted_app/test/dummy/config/webpacker.yml
test/test_app/config/webpacker_other_location.yml

Also fix `inline` to `inline_css` in some test files, though it didn't affect results because the default is `inline_css: true`.

Describe keys for dev_server in generated webpacker.yml

---

CHANGELOG.md
package.json
yarn.lock

Upgrade js dependencies and address known vulnerabilities.

Fix js vulnerabilities

---

.eslintrc.js
package/rules/babel.js
package/rules/jscommon.js

- Added indentation rule
- Fixed indentation issues

242 eslint check doesnt catch indentation errors

---

CHANGELOG.md

Fix mistake in PR link

---

docs/deployment.md

Add Heroku deployment hint to README

---

CHANGELOG.md
docs/v7_upgrade.md

Simplify the spelling change and v6 to 7 upgrade guideline

Update docs for spelling change

---

README.md

Add a link to the README file to access the v6.x branch.

Add link to 6-stable branch

---

Gemfile.development_dependencies

Just bump the spec-rails
- [~] Add/update test to cover these changes
- [~] Update documentation
- [~] Update CHANGELOG file

Safe to bump rspec-rails v6.

---

CHANGELOG.md
README.md
docs/react.md
docs/troubleshooting.md
docs/using_esbuild_loader.md
docs/v7_upgrade.md
lib/shakapacker/dev_server_runner.rb
package/__tests__/development-bc.js
package/__tests__/development.js
package/__tests__/index.js
package/__tests__/production-bc.js
package/__tests__/production.js
package/__tests__/staging-bc.js
package/__tests__/staging.js
package/__tests__/test-bc.js
package/__tests__/test.js
package/config.js
package/dev_server.js
package/env.js
package/environments/development.js
package/index.js
package/utils/configPath.js
package/utils/defaultConfigPath.js
package/utils/get_style_rule.js
package/utils/inliningCss.js
package/utils/snakeToCamelCase
package/webpackDevServerConfig.js

Change to an immutable base webpack config function as the default

---

README.md
package/__tests__/development-bc.js
package/__tests__/development.js
package/__tests__/production-bc.js
package/__tests__/production.js
package/__tests__/staging-bc.js
package/__tests__/staging.js
package/__tests__/test.js

A quick fix to include `generateWebpackConfig` name in the README file and in the tests.

Update documentation for webpack config

---

lib/install/config/webpack/webpack.config.js
package/index.js

Reflect changes related to #293 in the config file created in the installation task.

Import generateWebpackConfig in the base js config file script

---

README.md
docs/deployment.md

Properly document CDN support

---

CHANGELOG.md

Added missing 7.0.2 version into the changelog.

Update changelog for 7.0.2

---

.github/workflows/ruby-backward-compatibility.yml
CONTRIBUTING.md
README.md
docs/deployment.md
docs/using_esbuild_loader.md
docs/v6_upgrade.md
docs/v7_upgrade.md
lib/tasks/shakapacker/check_binstubs.rake
package/environments/__tests__/base-bc.js
package/environments/__tests__/development.js
package/environments/__tests__/production.js
rakelib/release.rake
spec/backward_compatibility_specs/compiler_spec.rb
spec/backward_compatibility_specs/configuration_spec.rb
spec/generator_specs/generator_spec.rb
spec/shakapacker/compiler_spec.rb
spec/shakapacker/configuration_spec.rb
spec/shakapacker/rake_tasks_spec.rb
spec/shakapacker/version_checker_spec.rb

I noticed a couple while working on other stuff, and so did a bigger review of the codebase.
There's a couple in here which might cause the tests to fail, and technically the renaming of a method that is public - I've stuck a deprecation warning in but honestly it's probably fine to just make the change.

chore: minor grammar fixes

---

lib/shakapacker/dev_server_runner.rb
lib/shakapacker/webpack_runner.rb

I missed this when updating #350 😞

fix: properly update `NODE_OPTIONS`

---

README.md

Fix minor issues in readme

---

package.json

Fix https://github.com/shakacode/shakapacker/issues/368
Thank you!

Add support of Yarn 4.x

---

.github/workflows/dummy.yml
.github/workflows/generator.yml
.github/workflows/jest.yml
.github/workflows/js-lint.yml
.github/workflows/rubocop.yml
.github/workflows/ruby-backward-compatibility.yml
.github/workflows/ruby.yml

Prevent duplication CI trigger.
-

Limit CI trigger to push on master and PRs

---

.github/workflows/generator.yml

_Remove this paragraph and describe the code changes in your pull request... were there any bugs you had fixed? If so, mention them. If these bugs have open GitHub issues, tag them here as well to keep the conversation linked._
Closes #395

Fix generator spec failure

---

CHANGELOG.md
package.json

> [!NOTE]
> I've tested with a local application by running `npm pack` and referencing shakapacker as `"file:../shakapacker/shakapacker-7.2.1.tgz"` in `package.json`. I'm not a javascript developer, so I may miss something important, please double check
Close #404

Allow compression-webpack-plugin 11

---

README.md

Fixes #387
Adds mentions of possible options of sass-loader implementations that user can install

Update Sass docs

---

.github/workflows/dummy.yml
.github/workflows/generator.yml
.github/workflows/jest.yml
.github/workflows/js-lint.yml
.github/workflows/rubocop.yml
.github/workflows/ruby.yml

This makes things a bit faster

ci: cancel in-progress jobs when new changes are pushed

---

.github/workflows/generator.yml
.github/workflows/ruby.yml
gemfiles/Gemfile-rails.7.1.x

ci: test against Rails 7.1

---

CHANGELOG.md
lib/tasks/shakapacker/check_binstubs.rake

feat!: remove `verify_file_existance` method

---

CHANGELOG.md
README.md
docs/v8_upgrade.md

docs: create upgrade guide for v8

---

.eslintrc.js
package.json
test/package/config.test.js
test/package/dev_server.test.js
test/package/development.test.js
test/package/env.test.js
test/package/environments/base.test.js
test/package/environments/development.test.js
test/package/environments/production.test.js
test/package/index.test.js
test/package/production.test.js
test/package/rules/file.test.js
test/package/rules/raw.test.js
test/package/staging.test.js
test/package/test.test.js
yarn.lock

This sets `eslint-plugin-jest` up with recommend rules from both the plugin and myself.
**Disclaimer: I'm a core maintainer of `eslint-plugin-jest`**

refactor: use `eslint-plugin-jest`

---

spec/dummy/Gemfile.lock
spec/dummy/yarn.lock

Fixes the dummy specs after gem update.

Fix dummy spec
